### Array Indexing

In [1]:
import numpy as np

#### 1-D Array Indexing

In [2]:
arr1 = np.arange(10,101,10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [7]:
arr1[3]

40

In [4]:
arr1[-4]

70

#### 2-D Array Indexing

In [5]:
arr2 = np.array([
    [1,2,3,],[4,5,6],[7,8,9],[10,11,12]
])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
arr2[2][1]

8

In [ ]:
arr2[3][2]

#### 3-D Array Indexing

In [11]:
arr3 = np.array([
    [[1,2,],[3,4]],
    [[5,6],[7,8]]
])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
arr3[0][1][0]

3