### Array Slicing

In [2]:
import numpy as np

#### 1-D Array Slicing

In [3]:
arr1  = np.arange(10,101,10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
arr2 = arr1[1:6]
arr2

array([20, 30, 40, 50, 60])

In [7]:
arr3 = arr1[1:6:2] # here the value refers to the increment of index by default iit is one(1)
arr3

array([20, 40, 60])

##### giving only one value inside []

In [8]:
arr4 = arr1[5:]
arr4

array([ 60,  70,  80,  90, 100])

In [10]:
arr5 = arr1[:5]
arr5

array([10, 20, 30, 40, 50])

##### negative indexing

In [12]:
arr6 = arr1[-4:-7:-1]
arr6

array([70, 60, 50])

#### 2-D Array Slicing

In [15]:
arr7 = np.array([
    [1,2,3,],[4,5,6],[7,8,9],[10,11,12]
])
arr7

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
arr8 = arr7[2,0:2] # here the first value refers to the row need to be sliced and th other two value(0;2) refers to the index of the rown need to be sliced
arr8

array([7, 8])

In [19]:
arr9 = arr7[1:3,0:3] # here we 1:3 is specifying which row need to be sliced and the other two value refers to the index of each row need to be sliced
arr9

array([[4, 5, 6],
       [7, 8, 9]])

#### 3-D Array Slicing

In [28]:
arr10 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])
arr10

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [30]:
arr11 = arr10[1, 0, 0:2]
arr11

array([7, 8])