# Numpy

## Two Dimensional Arrays

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [4]:
print(arr1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
arr1.ndim

2

In [7]:
arr2 = np.array([[10,20,30],[40,50,60]])

In [8]:
print(arr2)

[[10 20 30]
 [40 50 60]]


In [9]:
arr2.size

6

In [10]:
arr1.size

12