# Numpy

## Three Dimensional Array

In [2]:
import numpy as np

In [4]:
arr1 = np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
])

In [5]:
arr1.ndim

3

In [6]:
print(arr1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]


In [9]:
arr1.ndim

3