# Numpy Datatypes

In [2]:
import numpy as np

## Find Data Types Of An Array

In [6]:
arr1  = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1.dtype

dtype('int32')

In [9]:
arr2 = np.array([1.1,2.1,3.1,4.1,5.1])

In [10]:
arr2.dtype

dtype('float64')

In [11]:
arr3 = np.array(['a','b','c'])

In [12]:
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [14]:
arr3.dtype

dtype('<U1')

## Create An Array With Specified Data Type

In [21]:
arr4 = np.array([1,2,3,4,5],dtype=np.int64) #Here we are specifing datatype using the datatype's in the numpy, we can also do with the character code assigned to each dtype

In [22]:
arr4.dtype

dtype('int64')

In [19]:
arr5 = np.array([1,2,3,4,5], dtype=np.float16)

In [20]:
arr5.dtype

dtype('float16')

In [25]:
arr4 = np.array([1,2,3,4,5],dtype='i2') #Here we are specifing the character code assigned to dtype insted of using the datatype's in the numpy

In [26]:
arr4.dtype

dtype('int16')

## Convert Data Types

In [30]:
arr5 = np.array([1,2,3,4,5],dtype=np.int8)

In [31]:
arr5.dtype

dtype('int8')

In [32]:
arr8 = arr5.astype(np.float16)

In [33]:
arr8.dtype

dtype('float16')

In [34]:
arr8

array([1., 2., 3., 4., 5.], dtype=float16)

In [35]:
arr9 = arr7.astype(np.uint16)

In [36]:
arr9.dtype

dtype('uint16')

In [37]:
arr9

array([1, 2, 3, 4, 5], dtype=uint16)