# Reshape An Array

In [2]:
import numpy as np

## One Dimension To Two Dimension Array

In [3]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
new_arr1 = arr1.reshape(2,3)
new_arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
new_arr1.shape

(2, 3)

## One Dimension To Three Dimension Array

In [9]:
arr2 = np.array([1,2,3,4,5,6,7,8])
arr2.shape

(8,)

In [11]:
new_arr2 = arr2.reshape(2,2,2)
new_arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
new_arr2.shape

(2, 2, 2)

## Two Dimension To Two Dimension Array

In [13]:
arr3 = np.array([[1,2],[3,4],[5,6],[7,8]])

In [14]:
arr3.shape

(4, 2)

In [15]:
new_arr3 = arr3.reshape(2,4)

In [16]:
new_arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
new_arr3.shape

(2, 4)

## Two Dimension To Three Dimension Array

In [19]:
new_3d_arr3 = arr3.reshape(2,2,2)

In [20]:
new_3d_arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
new_3d_arr3.shape

(2, 2, 2)

## Three Dimension To Two Dimension Array

In [23]:
new_arr4 = new_3d_arr3.reshape(2,4)

In [24]:
new_arr4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Multi Dimension Array To One Dimension Array

In [26]:
new_3d_arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
new_arr5 = new_3d_arr3.reshape(-1)

In [28]:
new_arr5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
new_arr4.shape

(2, 4)

In [30]:
new_arr6 = new_arr4.reshape(-1)

In [31]:
new_arr6

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
new_arr6.shape

(8,)