# Shape Of An Array

In [15]:
import numpy as np

In [16]:
arr1 = np.array([1,2,3,4])

In [17]:
print(arr1)

[1 2 3 4]


In [18]:
np.shape(arr1)

(4,)

In [19]:
arr1.shape

(4,)

In [20]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
arr2.shape

(4, 3)

In [23]:
arr3 = np.array([
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
    [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
])

In [24]:
arr1.shape

(4,)